name: Linter

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, tokenizer
          coverage: none

      - name: Install dependencies
        run: |
          composer install --no-interaction --prefer-dist --no-scripts
          composer dump-autoload

      - name: Run PHPCS
        run: composer lint
